require('dotenv').config();

const {
  PORT = 3000,
  DATABASE_URL,
  JWT_SECRET,
  JWT_EXPIRY = '12h',
  ETHEREUM_RPC_URL,
  TWO_FA_SECRET_KEY,
  FRONTEND_URL = '*',

  // Smart contract addresses
  USER_MANAGEMENT_ADDRESS,
  DRUG_SUPPLY_CHAIN_ADDRESS,
  PRESCRIPTION_ADDRESS,
  REGULATOR_OVERSIGHT_ADDRESS,
} = process.env;

module.exports = {
  PORT: Number(PORT),
  DATABASE_URL,
  JWT_SECRET,
  JWT_EXPIRY,
  ETHEREUM_RPC_URL,
  TWO_FA_SECRET_KEY,
  FRONTEND_URL,

  USER_MANAGEMENT_ADDRESS,
  DRUG_SUPPLY_CHAIN_ADDRESS,
  PRESCRIPTION_ADDRESS,
  REGULATOR_OVERSIGHT_ADDRESS,
};
