const ROLES = {
  ADMIN: "ADMIN",
  REGULATOR: "REGULATOR",
  DOCTOR: "DOCTOR",
  PHARMACIST: "PHARMACIST",
  MANUFACTURER: "MANUFACTURER",
  DISTRIBUTOR: "DISTRIBUTOR",
  PATIENT: "PATIENT",
};

export default ROLES;
